default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: localhost
  username: ntherm
  password: database
  database: leads_database_default


development:
  <<: *default
  database: leads_database_dev

test:
  <<: *default
  database: leads_database_test

production:
  <<: *default
  database: leads_database_production
