default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000

development:
  <<: *default
  database: leads_database_dev

test:
  <<: *default
  database: leads_database_test

production:
  <<: *default
  database: leads_database_production
